package httpapi

import "html/template"

var loginTemplate = template.Must(template.New("login").Parse(`<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Teleproxy Login</title>
<style>
:root{font-family:Inter,ui-sans-serif,system-ui,sans-serif;color-scheme:dark;background:#0b1020;color:#eef2ff}*{box-sizing:border-box}body{margin:0;min-height:100vh;display:grid;place-items:center;background:radial-gradient(circle at 20% 10%,#172554 0,#0b1020 42%)}main{width:min(92vw,420px);padding:32px;border:1px solid #26324f;border-radius:18px;background:#11182a;box-shadow:0 24px 70px #0007}h1{margin:0 0 6px;font-size:28px}p{color:#aebbd6;margin:0 0 24px}label{display:block;margin:14px 0 7px;font-size:14px}input{width:100%;border:1px solid #34415f;border-radius:10px;padding:12px 13px;background:#0c1323;color:#fff;font:inherit}input:focus{outline:2px solid #7c9cff;outline-offset:1px}button{width:100%;margin-top:20px;border:0;border-radius:10px;padding:12px 14px;background:#dbe6ff;color:#111827;font-weight:700;cursor:pointer}.error{padding:10px 12px;border-radius:10px;background:#35171d;color:#ffc8d0;margin-bottom:14px}small{display:block;margin-top:18px;color:#7483a4}</style>
</head>
<body><main><h1>Teleproxy</h1><p>Administrator sign in</p>{{if .Error}}<div class="error" role="alert">{{.Error}}</div>{{end}}<form method="post" action="/login"><input type="hidden" name="csrf" value="{{.CSRF}}"><label for="username">Username</label><input id="username" name="username" autocomplete="username" required autofocus><label for="password">Password</label><input id="password" name="password" type="password" autocomplete="current-password" required><button type="submit">Sign in</button></form><small>Control Plane access</small></main></body></html>`))

var dashboardTemplate = template.Must(template.New("dashboard").Parse(`<!doctype html>
<html lang="en">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Teleproxy Overview</title><style>
:root{font-family:Inter,ui-sans-serif,system-ui,sans-serif;color-scheme:dark;background:#0b1020;color:#eef2ff}body{margin:0}header{display:flex;justify-content:space-between;align-items:center;padding:18px 5vw;border-bottom:1px solid #24304c;background:#10172a}main{padding:36px 5vw}.hero{display:flex;justify-content:space-between;gap:18px;align-items:flex-end;margin-bottom:22px}.hero h1{margin:0 0 6px;font-size:32px}.hero p{margin:0;color:#9aa8c4}.actions{display:flex;gap:10px;flex-wrap:wrap}.button{display:inline-flex;align-items:center;justify-content:center;min-height:40px;padding:10px 14px;border-radius:10px;text-decoration:none;font-weight:700;border:1px solid #425778;background:#142239;color:#eaf1ff}.button.primary{background:#dbe6ff;color:#111827;border-color:#dbe6ff}.status-grid,.manage-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(190px,1fr));gap:14px}.status-card,.manage-card{padding:18px;border:1px solid #26324f;border-radius:14px;background:#0d1425}.status-card .label{display:block;color:#9aa8c4;font-size:12px;margin-bottom:8px}.status-card .value{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;overflow-wrap:anywhere}.section{margin-top:24px}.section h2{margin:0 0 12px}.manage-card{display:block;color:#eef2ff;text-decoration:none}.manage-card:hover{border-color:#4a6591;background:#111d31}.manage-card strong{display:block;margin-bottom:6px}.manage-card span{color:#8fa2c1;font-size:13px;line-height:1.4}.logout{border:1px solid #52617d;border-radius:9px;padding:9px 12px;background:#18223a;color:#fff;cursor:pointer}@media(max-width:700px){.hero{align-items:flex-start;flex-direction:column}}
</style></head>
<body>
<header><strong>Teleproxy</strong><form method="post" action="/logout"><input type="hidden" name="csrf" value="{{.CSRF}}"><button class="logout" type="submit">Sign out</button></form></header>
<main>
<section class="hero"><div><h1>Overview</h1><p>Signed in as <strong>{{.Username}}</strong>. The common tasks are one click away.</p></div><div class="actions"><a class="button primary" href="/nodes#quick-create">Create Proxy</a><a class="button" href="/settings">Configure Bot</a></div></section>
<section class="status-grid" aria-label="System status"><div class="status-card"><span class="label">Control Plane</span><strong class="value">{{.PanelState}}</strong></div><div class="status-card"><span class="label">Database</span><strong class="value">{{.DatabaseState}}</strong></div><div class="status-card"><span class="label">Global Proxy</span><strong class="value">{{.ProxyState}}</strong></div><div class="status-card"><span class="label">Proxy read-only mode</span><strong class="value">{{if .ProxyReadOnlyKnown}}{{if .ProxyReadOnly}}yes{{else}}no{{end}}{{else}}not applicable{{end}}</strong></div></section>
<section class="section"><h2>Manage</h2><div class="manage-grid"><a class="manage-card" href="/users"><strong>Users</strong><span>Accounts, proxy state and provisioning status.</span></a><a class="manage-card" href="/nodes"><strong>Proxies</strong><span>Quick add and infrastructure metadata.</span></a><a class="manage-card" href="/forced-join"><strong>Required Channels</strong><span>Channels users must join before proxy access.</span></a><a class="manage-card" href="/sponsors"><strong>Sponsors</strong><span>Sponsor profiles and campaign metadata.</span></a><a class="manage-card" href="/bot-content"><strong>Bot Content</strong><span>Welcome, proxy and referral copy.</span></a><a class="manage-card" href="/referrals"><strong>Referrals</strong><span>Attribution history and reward settings.</span></a><a class="manage-card" href="/settings"><strong>Settings</strong><span>Telegram Bot runtime and credit defaults.</span></a><a class="manage-card" href="/admins"><strong>Administrators</strong><span>Administrator accounts and access inventory.</span></a><a class="manage-card" href="/audit-log"><strong>Audit Log</strong><span>Read-only administrative activity history.</span></a><a class="manage-card" href="/system"><strong>System</strong><span>Control, database and proxy health.</span></a></div></section>
</main></body></html>`))
